/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.exp1.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.eclipse.xtext.junit4.validation.ValidationTestHelper
import org.junit.Test
import org.junit.runner.RunWith
import org.xtext.example.exp1.exp1.Exp1
import org.xtext.example.exp1.tests.Exp1InjectorProvider

@RunWith(XtextRunner)
@InjectWith(Exp1InjectorProvider)
class Exp1ParsingTest {
	@Inject
	extension ValidationTestHelper validationTestHelper

	@Inject
	extension ParseHelper<Exp1>

	@Test
	def testaExpressaoSoma() {
		val model = '''
			10+5
		'''.parse
		validationTestHelper.assertNoErrors(model)
	}

	@Test
	def testaExpressaoSub() {
		val model = '''
			15-5
		'''.parse
		validationTestHelper.assertNoErrors(model)
	}
	
	//rever depois
	@Test
	def testaExpressaoAnd() {
		val model = '''
			true and false
		'''.parse
		validationTestHelper.assertNoErrors(model)
	}
	
	
	@Test
	def testaExpressaoSomaValor() {
		val model = '''
			15+5
		'''.parse
		validationTestHelper.assertNoErrors(model)
	}
}
