/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.exp1.exp1;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.exp1.exp1.Exp1Factory
 * @model kind="package"
 * @generated
 */
public interface Exp1Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "exp1";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/exp1/Exp1";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "exp1";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Exp1Package eINSTANCE = org.xtext.example.exp1.exp1.impl.Exp1PackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.exp1.exp1.impl.Exp1Impl <em>Exp1</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.exp1.exp1.impl.Exp1Impl
   * @see org.xtext.example.exp1.exp1.impl.Exp1PackageImpl#getExp1()
   * @generated
   */
  int EXP1 = 0;

  /**
   * The feature id for the '<em><b>Expressoes</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP1__EXPRESSOES = 0;

  /**
   * The number of structural features of the '<em>Exp1</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP1_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.exp1.exp1.Exp1 <em>Exp1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp1</em>'.
   * @see org.xtext.example.exp1.exp1.Exp1
   * @generated
   */
  EClass getExp1();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.exp1.exp1.Exp1#getExpressoes <em>Expressoes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Expressoes</em>'.
   * @see org.xtext.example.exp1.exp1.Exp1#getExpressoes()
   * @see #getExp1()
   * @generated
   */
  EAttribute getExp1_Expressoes();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  Exp1Factory getExp1Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.exp1.exp1.impl.Exp1Impl <em>Exp1</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.exp1.exp1.impl.Exp1Impl
     * @see org.xtext.example.exp1.exp1.impl.Exp1PackageImpl#getExp1()
     * @generated
     */
    EClass EXP1 = eINSTANCE.getExp1();

    /**
     * The meta object literal for the '<em><b>Expressoes</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXP1__EXPRESSOES = eINSTANCE.getExp1_Expressoes();

  }

} //Exp1Package
