/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.exp1.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.xtext.example.exp1.ide.contentassist.antlr.internal.InternalExp1Parser;
import org.xtext.example.exp1.services.Exp1GrammarAccess;

public class Exp1Parser extends AbstractContentAssistParser {

	@Inject
	private Exp1GrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalExp1Parser createParser() {
		InternalExp1Parser result = new InternalExp1Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getExpAritmeticaAccess().getAlternatives_1_0(), "rule__ExpAritmetica__Alternatives_1_0");
					put(grammarAccess.getExpUnariaAccess().getAlternatives(), "rule__ExpUnaria__Alternatives");
					put(grammarAccess.getValorConcretoAccess().getAlternatives(), "rule__ValorConcreto__Alternatives");
					put(grammarAccess.getExpCondicionalOrAccess().getGroup(), "rule__ExpCondicionalOr__Group__0");
					put(grammarAccess.getExpCondicionalOrAccess().getGroup_1(), "rule__ExpCondicionalOr__Group_1__0");
					put(grammarAccess.getExpCondicionalAndAccess().getGroup(), "rule__ExpCondicionalAnd__Group__0");
					put(grammarAccess.getExpCondicionalAndAccess().getGroup_1(), "rule__ExpCondicionalAnd__Group_1__0");
					put(grammarAccess.getExpIgualdadeAccess().getGroup(), "rule__ExpIgualdade__Group__0");
					put(grammarAccess.getExpIgualdadeAccess().getGroup_1(), "rule__ExpIgualdade__Group_1__0");
					put(grammarAccess.getExpAritmeticaAccess().getGroup(), "rule__ExpAritmetica__Group__0");
					put(grammarAccess.getExpAritmeticaAccess().getGroup_1(), "rule__ExpAritmetica__Group_1__0");
					put(grammarAccess.getExpConcatenacaoAccess().getGroup(), "rule__ExpConcatenacao__Group__0");
					put(grammarAccess.getExpConcatenacaoAccess().getGroup_1(), "rule__ExpConcatenacao__Group_1__0");
					put(grammarAccess.getExpUnariaAccess().getGroup_0(), "rule__ExpUnaria__Group_0__0");
					put(grammarAccess.getExpUnariaAccess().getGroup_1(), "rule__ExpUnaria__Group_1__0");
					put(grammarAccess.getExpUnariaAccess().getGroup_2(), "rule__ExpUnaria__Group_2__0");
					put(grammarAccess.getExp1Access().getExpressoesAssignment(), "rule__Exp1__ExpressoesAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalExp1Parser typedParser = (InternalExp1Parser) parser;
			typedParser.entryRuleExp1();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public Exp1GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Exp1GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
